// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg40AED-VYymiWAbLXrWsmSLbI89FTTRk',
    appId: '1:508605399608:web:a21a01210aad47af4d9ccd',
    messagingSenderId: '508605399608',
    projectId: 'curemate-application',
    authDomain: 'curemate-application.firebaseapp.com',
    storageBucket: 'curemate-application.firebasestorage.app',
    measurementId: 'G-Q9QPEPZ04J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMS23FMdAamSwpy3s6C61-N6qNVOZAduQ',
    appId: '1:508605399608:android:dfbd0c0b0d1f5e3d4d9ccd',
    messagingSenderId: '508605399608',
    projectId: 'curemate-application',
    storageBucket: 'curemate-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Wi1ML8wzl6zCsZGRoaoX9swZiVOOaSw',
    appId: '1:508605399608:ios:0cc2109beac357d04d9ccd',
    messagingSenderId: '508605399608',
    projectId: 'curemate-application',
    storageBucket: 'curemate-application.firebasestorage.app',
    iosBundleId: 'com.example.cureMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Wi1ML8wzl6zCsZGRoaoX9swZiVOOaSw',
    appId: '1:508605399608:ios:0cc2109beac357d04d9ccd',
    messagingSenderId: '508605399608',
    projectId: 'curemate-application',
    storageBucket: 'curemate-application.firebasestorage.app',
    iosBundleId: 'com.example.cureMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg40AED-VYymiWAbLXrWsmSLbI89FTTRk',
    appId: '1:508605399608:web:c69ef0471ce5eb5e4d9ccd',
    messagingSenderId: '508605399608',
    projectId: 'curemate-application',
    authDomain: 'curemate-application.firebaseapp.com',
    storageBucket: 'curemate-application.firebasestorage.app',
    measurementId: 'G-HET5546EFR',
  );
}
